# Generated by Django 3.0.2 on 2021-07-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='code',
        ),
    ]
