# Generated by Django 3.0.3 on 2020-07-23 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_auto_20200722_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_township',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
