# Generated by Django 3.0.3 on 2020-07-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_house_house_township'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_deposit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_rent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_rooms_number',
            field=models.IntegerField(),
        ),
    ]
