# Generated by Django 3.0.3 on 2020-07-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_auto_20200723_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['house_township', 'house_area', 'house_kind', 'house_rooms_number', 'house_rent', 'house_deposit']},
        ),
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='img/avatars/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_image',
            field=models.ImageField(upload_to='img/houses/'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='img/avatars/'),
        ),
    ]
