# Generated by Django 3.0.3 on 2020-08-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_auto_20200730_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='kind_desire',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='rooms_number_desire',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
