# Generated by Django 3.1.7 on 2021-03-06 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_auto_20200804_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_creation_day',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
