# Generated by Django 3.1.7 on 2021-05-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0007_house_house_creation_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='area_desire',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='township_desire',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
