# Generated by Django 3.1.7 on 2021-07-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0008_auto_20210512_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='area_desire',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='township_desire',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
