# Generated by Django 3.1.7 on 2021-07-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0009_auto_20210710_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='concluded',
            field=models.BooleanField(default=0),
        ),
    ]
